name: Test Link Rewrites

on: [deployment_status]

jobs:
  test-link-rewrites:
    if: github.event.deployment_status.state == 'success'
    # TODO update commit sha referenced before merging
    uses: hashicorp/dev-portal/.github/workflows/docs-content-link-rewrites-e2e.yml@amb.adjust-link-rewrite-script
    with:
      repo-owner: "hashicorp"
      repo-name: "consul"
      commit-sha: ${{ github.sha }}
      main-branch-preview-url: "https://consul-git-main-hashicorp.vercel.app/"
      # Workflow is only intended to run for one single migration PR
      # This variable does not need to be updated
      pr-branch-preview-url: "https://consul-git-docs-ambmigrate-link-formats-hashicorp.vercel.app/"
